swig -c++ -python pathfinding.i
g++ -fpic -c pathfinding.h pathfinding_wrap.cxx pathfinding.cpp -I C:\Users\loope\AppData\Local\Programs\Python\Python37\include
gcc -shared pathfinding_wrap.o pathfinding.o C:\Users\loope\AppData\Local\Programs\Python\Python37\python37.dll -o _pathfinding.pyd -lstdc++